### ISSUE TITLE
No documentation on how to build project

### ISSUE THREAD

**Issue by Omcsesz** [oleg-chibikov/Scar.Common#1]
Hello, Oleg!

Can you please provide documentation for how to build the project/what dependencies are needed?

**Comment by oleg-chibikov** [comment]
Hey, @Omcsesz 
I've just noticed your comment. I didn't expect anyone else except for myself uses this actually:)
The project has been reworked since your comment and now should be built like a regular .Net project - from Visual Studio with Rebuild All command.
It used to use private nuget repo which I later found too cumbersome. So now each library just references the other projects.
